/* tslint:disable */
/* eslint-disable */
/**
 * OpenWeatherMapp API
 * Get the current weather, daily forecast for 16 days, and a three-hour-interval forecast for 5 days for your city. Helpful stats, graphics, and this day in history charts are available for your reference. Interactive maps show precipitation, clouds, pressure, wind around your location stations. Data is available in JSON, XML, or HTML format. **Note**: This sample Swagger file covers the `current` endpoint only from the OpenWeatherMap API. <br/><br/> **Note**: All parameters are optional, but you must select at least one parameter. Calling the API by city ID (using the `id` parameter) will provide the most precise location results.
 *
 * The version of the OpenAPI document: 2.5
 * Contact: some_email@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Main
 */
export interface Main {
    /**
     * Temperature. Unit Default: Kelvin, Metric: Celsius, Imperial: Fahrenheit.
     * @type {number}
     * @memberof Main
     */
    temp?: number;
    /**
     * Atmospheric pressure (on the sea level, if there is no sea_level or grnd_level data), hPa
     * @type {number}
     * @memberof Main
     */
    pressure?: number;
    /**
     * Humidity, %
     * @type {number}
     * @memberof Main
     */
    humidity?: number;
    /**
     * Minimum temperature at the moment. This is deviation from current temp that is possible for large cities and megalopolises geographically expanded (use these parameter optionally). Unit Default: Kelvin, Metric: Celsius, Imperial: Fahrenheit.
     * @type {number}
     * @memberof Main
     */
    temp_min?: number;
    /**
     * Maximum temperature at the moment. This is deviation from current temp that is possible for large cities and megalopolises geographically expanded (use these parameter optionally). Unit Default: Kelvin, Metric: Celsius, Imperial: Fahrenheit.
     * @type {number}
     * @memberof Main
     */
    temp_max?: number;
    /**
     * Atmospheric pressure on the sea level, hPa
     * @type {number}
     * @memberof Main
     */
    sea_level?: number;
    /**
     * Atmospheric pressure on the ground level, hPa
     * @type {number}
     * @memberof Main
     */
    grnd_level?: number;
}


