/* tslint:disable */
/* eslint-disable */
/**
 * OpenWeatherMap API
 * Get the current weather, daily forecast for 16 days, and a three-hour-interval forecast for 5 days for your city. Helpful stats, graphics, and this day in history charts are available for your reference. Interactive maps show precipitation, clouds, pressure, wind around your location stations. Data is available in JSON, XML, or HTML format. **Note**: This sample Swagger file covers the `current` endpoint only from the OpenWeatherMap API. <br/><br/> **Note**: All parameters are optional, but you must select at least one parameter. Calling the API by city ID (using the `id` parameter) will provide the most precise location results.
 *
 * The version of the OpenAPI document: 2.5
 * Contact: some_email@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Clouds } from './clouds';
import { Coord } from './coord';
import { Main } from './main';
import { Rain } from './rain';
import { Snow } from './snow';
import { Sys } from './sys';
import { Weather } from './weather';
import { Wind } from './wind';

/**
 * 
 * @export
 * @interface Model200
 */
export interface Model200 {
    /**
     * 
     * @type {Coord}
     * @memberof Model200
     */
    coord?: Coord;
    /**
     * (more info Weather condition codes)
     * @type {Array<Weather>}
     * @memberof Model200
     */
    weather?: Array<Weather>;
    /**
     * Internal parameter
     * @type {string}
     * @memberof Model200
     */
    base?: string;
    /**
     * 
     * @type {Main}
     * @memberof Model200
     */
    main?: Main;
    /**
     * Visibility, meter
     * @type {number}
     * @memberof Model200
     */
    visibility?: number;
    /**
     * 
     * @type {Wind}
     * @memberof Model200
     */
    wind?: Wind;
    /**
     * 
     * @type {Clouds}
     * @memberof Model200
     */
    clouds?: Clouds;
    /**
     * 
     * @type {Rain}
     * @memberof Model200
     */
    rain?: Rain;
    /**
     * 
     * @type {Snow}
     * @memberof Model200
     */
    snow?: Snow;
    /**
     * Time of data calculation, unix, UTC
     * @type {number}
     * @memberof Model200
     */
    dt?: number;
    /**
     * 
     * @type {Sys}
     * @memberof Model200
     */
    sys?: Sys;
    /**
     * City ID
     * @type {number}
     * @memberof Model200
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Model200
     */
    name?: string;
    /**
     * Internal parameter
     * @type {number}
     * @memberof Model200
     */
    cod?: number;
}


