/* tslint:disable */
/* eslint-disable */
/**
 * OpenWeatherMap API
 * Get the current weather, daily forecast for 16 days, and a three-hour-interval forecast for 5 days for your city. Helpful stats, graphics, and this day in history charts are available for your reference. Interactive maps show precipitation, clouds, pressure, wind around your location stations. Data is available in JSON, XML, or HTML format. **Note**: This sample Swagger file covers the `current` endpoint only from the OpenWeatherMap API. <br/><br/> **Note**: All parameters are optional, but you must select at least one parameter. Calling the API by city ID (using the `id` parameter) will provide the most precise location results.
 *
 * The version of the OpenAPI document: 2.5
 * Contact: some_email@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Weather
 */
export interface Weather {
    /**
     * Weather condition id
     * @type {number}
     * @memberof Weather
     */
    id?: number;
    /**
     * Group of weather parameters (Rain, Snow, Extreme etc.)
     * @type {string}
     * @memberof Weather
     */
    main?: string;
    /**
     * Weather condition within the group
     * @type {string}
     * @memberof Weather
     */
    description?: string;
    /**
     * Weather icon id
     * @type {string}
     * @memberof Weather
     */
    icon?: string;
}


